baseURL = "https://waterlens.moe/"
languageCode = "en-us"
title = "Waterlens' Blog"
theme = "cactus"
googleAnalytics = "UA-198163789-1"
disqusShortname = "waterlens"

[markup]
  [markup.highlight]
    codeFences = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[params]
  description = "This is Waterlens' blog."
  mainSection = "posts"
  showAllPostsOnHomePage = true
  rss = true
  logo = "images/logo.svg"
  googleAnalyticsAsync = true
  showReadTime = true
  colortheme = "white"

[params.comments]
  enabled = true

[[params.social]]
  name = "github"
  link = "https://github.com/waterlens"

[[params.social]]
  name = "twitter"
  link = "https://twitter.com/water_lens"
