baseURL = "http://waterlens.moe/"
languageCode = "en-us"
title = "Waterlens' Blog"
theme = "cactus"
googleAnalytics = "UA-198163789-1"
disqusShortname = "waterlens"
copyright = "Waterlens"

[markup]
  [markup.highlight]
    codeFences = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[params]
  description = "This is Waterlens' blog."
  mainSection = "posts"
  showAllPostsOnHomePage = true
  rss = true
  [params.comments]
    enabled = true

[[params.social]]
  name = "github"
  link = "https://github.com/waterlens"

[[params.social]]
  name = "twitter"
  link = "https://twitter.com/water_lens"
